name: event_hub_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.5.0
  flutter_svg: ^2.2.3
  syncfusion_flutter_sliders: ^32.2.7

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
          weight: 400
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf
          weight: 800
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
          weight: 900